In [ ]:
!pip install -U plotly

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
pd.options.plotting.backend = "plotly"

In [ ]:
x = np.linspace(-10, 10, 100)
z = 1/(1 + np.exp(-x))
z_derivative = z * (1 - z)

# Sigmoid Function

In [39]:
df = pd.DataFrame(dict(
    x = x,
    z = z
))
fig = df.plot.scatter(x="x", y="z")
fig.show()

# Derivative of the Sigmoid Function

In [40]:
df = pd.DataFrame(dict(
    x = x,
    z = z,
    z_derivative = z_derivative
))
fig = df.plot.scatter(x="x", y="z_derivative")
fig.show()

# Sigmoid Function with Derivative of the Sigmoid Function

In [41]:
df = pd.DataFrame(dict(
    x = x,
    z = z,
    z_derivative = z_derivative
))
fig = df.plot.scatter(x="x", y=["z_derivative", "z"])
fig.show()

# Case 1 

In [42]:
x = np.array([0, 2])

In [43]:
z = 1/(1 + np.exp(-x))

In [44]:
z

array([0.5       , 0.88079708])

In [45]:
z_derivative = z * (1 - z)

In [46]:
z_derivative

array([0.25      , 0.10499359])

In [47]:
'{0:.8f}'.format(float((z_derivative[1] - z_derivative[0])))

'-0.14500641'

# Case 2

In [48]:
x = np.array([10, 20])

In [49]:
z = 1/(1 + np.exp(-x))

In [50]:
z

array([0.9999546, 1.       ])

In [52]:
z_derivative = z * (1 - z)

In [53]:
z_derivative

array([4.53958077e-05, 2.06115369e-09])

In [54]:
'{0:.8f}'.format(float((z_derivative[1] - z_derivative[0])))

'-0.00004539'